name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_NAME: "aboutme"
  BUILD_IMAGE_NAME: "tomekskr/aboutme"
jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and export
      uses: docker/build-push-action@v5
      with:
        context: src/
        tags: ${{ env.BUILD_IMAGE_NAME }}:latest
        outputs: type=docker,dest=./artifacts/aboutme.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: aboutme
        path: ./artifacts
        
  docker_push:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    needs: docker_build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: aboutme
          path: ./artifacts
      - name: Load image
        run: |
          docker load --input ./artifacts/aboutme.tar
          docker image ls -a
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        run: docker push ${{ env.BUILD_IMAGE_NAME }} -a
