name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_NAME: "aboutme"
  BUILD_IMAGE_NAME: "tomekskr/aboutme"
jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - run: mkdir -p ./artifacts
    - name: Build and export
      uses: docker/build-push-action@v5
      with:
        tags: ${{ env.BUILD_IMAGE_NAME }}:latest
        outputs: type=docker,dest=./artifacts/aboutme.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: aboutme
        path: ./artifacts
        
  docker_push:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    needs: docker_build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: aboutme
          path: ./artifacts
      - name: Load image
        run: |
          docker load --input ./artifacts/aboutme.tar
          docker image ls -a
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        run: docker push ${{ env.BUILD_IMAGE_NAME }} -a
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    needs: docker_push
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_IP }}
          username: ${{ secrets.INSTANCE_LOGIN }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop $(docker ps | grep aboutme | awk '{print $1}') &&
            docker run -dp 3000:3000 tomekskr/aboutme:latest
          
